# Generated by Django 4.1.3 on 2022-11-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='deadline',
            field=models.DateTimeField(blank=True, max_length=20, null=True, verbose_name='Срок'),
        ),
    ]
