# Generated by Django 4.1.3 on 2022-11-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_article_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
    ]
