# Generated by Django 4.1.3 on 2022-11-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_article_deadline_remove_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='deadline',
            field=models.DateTimeField(blank=True, max_length=20, null=True, verbose_name='Время на выполнение'),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
